config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title %><br> <br>
  <%= f.text_field :title %> <br> <br>
  <%= f.label :content %> <br> <br>
  <%= f.text_field :content %> <br> <br>
  <%= f.submit %>
<% end %>
<h1><%= link_to '🔙', articles_path %></h1>

app/views/articles/edit.html.erb
<div class="container text-center">
  <h1>Editing article</h1>
  <%= render "form", article: @article %>
</div>

app/views/articles/index.html.erb
<div class="container text-center">
  <% @articles.each do |article| %>
    <h2><%= link_to article.title, article_path(article) %></h2>
    <p><%= article.content %></p>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="container text-center">
  <h1>New article</h1>
  <%= render "form", article: @article %>
</div>

app/views/articles/show.html.erb
<div class="container text-center">
  <div class="title border-bottom">
    <h1><%= @article.title %></h1>
    <h1><%= link_to '✏️', edit_article_path %></h1>
    <h1><%= link_to '🗑', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %></h1>
  </div>
  <p> <%= @article.content %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <div class="nav border">
      <h1><%= link_to 'Wikinimous', articles_path %></h1>
      <p><%= link_to 'New article', new_article_path %></p>
    </div>
    <%= yield %>
  </body>
</html>